### ISSUE TITLE
[Dark Mode] Browse stations theming broken

### ISSUE THREAD

**Issue by Stanzilla** [gmusic-utils/gmusic-theme.js#73]
**OS:**
Windows 8.1 x64
**Issue Descriptions:**
Tab texts are a dark/black text color on black background
**Steps to Reproduce:**
Hamburger menu => Browse Stations => 
![google play music desktop player_2017-06-05_22-15-53](https://cloud.githubusercontent.com/assets/75278/26801295/b789d560-4a3c-11e7-9cc2-a55c4dfff13d.png)

**Comment by Alipoodle** [comment]
![image](https://b.catgirlsare.sexy/0z09.png)
Same on Free GPM top unless it's the same
(colour is CSS)

Edit: This seems to have been fix since next check.

**Comment by Alipoodle** [comment]
🤔 So it seems that this is a very few time that it happens.... but it seems that Randomly it will load another "version" of GPM with different names, as again i have this on the Free version of GPM.
![Example](https://puu.sh/wtX7c/df5afa55cc.png)
*note i'm running a custom CSS file and is dark theme*

**Comment by jostrander** [comment]
![image](https://user-images.githubusercontent.com/760989/27593684-c591f6f2-5b25-11e7-8f65-a2ad3f7911e0.png)

Top charts are also not correct any longer.

**Comment by MarshallOfSound** [comment]
Fixed in master

**Comment by sylmarien** [comment]
I think I am still experiencing this bug (even after updating to 4.3.0 and doing a fresh install)
![gpmdp_bug1](https://user-images.githubusercontent.com/8776275/27834269-57d64fbc-60a4-11e7-95e0-c80e1f3bdddb.png)
![gpmdp_bug2](https://user-images.githubusercontent.com/8776275/27834270-57d952d4-60a4-11e7-823a-d94ec699c3b1.png)

I am on Windows 10 and I am using the dark mode.

EDIT: After testing, also experiencing the same problem on Linux (Ubuntu 16.04)

**Comment by MarshallOfSound** [comment]
The GPMDP release with this fix will be 4.4.0 and it hasn't been released yet
